"""adds Order model

Revision ID: 578cd5991d23
Revises: 
Create Date: 2026-04-02 14:34:18.005363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578cd5991d23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
